---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ops-exercise::default]
    attributes:
