name             'ops-exercise'
maintainer       'Ryan LeViseur'
description      'Wordpress on LEMP stack'
long_description 'Implements a LEMP stack and Wordpress CMS'
version          '0.1.0'

supports 'ubuntu', '= 14.04'

depends 'apt'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'database'
depends 'hhvm'
depends 'wordpress'
depends 'os-hardening'
depends 'ssh-hardening'
